INSERT INTO plants (class, name, water, place, level)
VALUES ('Agave', 'Jahrhundertpflanze', 10, 'sun', 'easy'),
	('Aglaonema', 'Kolbenpfaden', 7, 'cloud', 'easy'),
	('Alocasia', 'Elefantenohr', 3, 'sun', 'hard'),
	('Aloe Vera', 'Wüstenlilie', 10, 'sun', 'easy'),
	('Anthurium', 'Flamingoblumen', 7, 'partly', 'medium'),
	('Aralia', 'Polyscias', 3, 'partly', 'medium'),
	('Areca', 'Goldfruchtpalme', 3, 'partly', 'medium'),
	('Asparagus', 'Zier-Spargel', 7, 'partly', 'medium'),
	('Aspidistra', 'Schusterpalme', 7, 'partly', 'easy'),
	('Asplenium', 'Nestfarn', 3, 'medium', 'medium'),
	('Beaucarnea', 'Elefantenfuß', 10, 'sun', 'easy'),
	('Begonia', 'Forellenbegonie', 3, 'partly', 'hard'),
	('Cactaceae', 'Kaktus', 10, 'sun', 'easy'),
	('Caladium', 'Kaladie', 7, 'partly', 'hard'),
	('Calathea', 'Pfeilwurze', 3, 'cloud', 'hard'),
	('Caryota', 'Fischschwanzpalme', 3, 'cloud', 'easy'),
	('Ceropegia', 'Leuchterblume', 10, 'partly', 'easy'),
	('Chamaedorea', 'Bergpalme', 3, 'partly', 'medium'),
	('Chlorophytum', 'Grünlilie', 7, 'partly', 'easy'),
	('Cissus', 'Klimme', 7, 'partly', 'medium'),
	('Clusia', 'Balsamapfel', 7, 'partly', 'easy'),
	('Coffea Arabica', 'Kaffeepflanze', 7, 'partly', 'medium'),
	('Cordyline', 'Keulenlilie', 7, 'partly', 'medium'),
	('Crassula', 'Jadestrauch', 10, 'sun', 'easy'),
	('Croton', 'Wunderstrauch', 3, 'sun', 'medium'),
	('Dieffenbachia', 'Schweigrohr', 7, 'partly', 'medium'),
	('Dracaena', 'Drachenbaum', 10, 'cloud', 'easy'),
	('Echeveria', '', 10, 'sun', 'easy'),
	('Epiphyllum', 'Sägekaktus', 10, 'partly', 'easy'),
	('Fatsia', 'Zimmeraralie', 7, 'partly', 'medium'),
	('Ficus', 'Gummibaum', 3, 'sun', 'easy'),
	('Hedera', 'Efeu', 3, 'sun', 'medium'),
	('Heteropanax', '', 3, 'sun', 'medium'),
	('Homalomena', '', 3, 'partly', 'easy'),
	('Howea Fosteriana', 'Kentia-Palme', 3, 'cloud', 'easy'),
	('Licuala Grandis', 'Fächerpalme', 7, 'partly', 'hard'),
	('Maranta', 'Gebetspflanze', 3, 'partly', 'medium'),
	('Monstera', 'Fensterblatt', 7, 'cloud', 'easy'),
	('Musa', 'Bananenpflanze', 3, 'sun', 'medium'),
	('Nephrolepis', 'Schwertfarn', 3, 'partly', 'hard'),
	('Pachira', 'Glückskastanie', 10, 'partly', 'easy'),
	('Peperomia', 'Zwergpfeffer', 7, 'partly', 'medium'),
	('Phalaenopsis', 'Orchidee', 10, 'sun', 'hard'),
	('Philodendron', 'Baumfreund', 7, 'cloud', 'easy'),
	('Phlebodium', 'Tüpfelfarn', 3, 'cloud', 'medium'),
	('Phoenix', 'Dattelpalme', 3, 'sun', 'hard'),
	('Pilea', 'Pfannkuchenpflanze', 7, 'partly', 'medium'),
	('Platycerium', 'Geweihfarn', 7, 'partly', 'medium'),
	('Rhapis', 'Steckenpalme', 10, 'cloud', 'easy'),
	('Rhipsalis', 'Korallenkaktus', 10, 'cloud', 'medium'),
	('Sansevieria', 'Bogenhanf', 10, 'partly', 'easy'),
	('Schefflera', 'Strahlenaralie', 3, 'partly', 'easy'),
	('Scindapsus', 'Efeutute', 7, 'partly', 'medium'),
	('Spathiphyllum', 'Einblatt', 3, 'partly', 'easy'),
	('Strelitzia', 'Paradiesvogelblume', 3, 'sun', 'easy'),
	('Syngonium', 'Arrowhead', 7, 'partly', 'medium'),
	('Tradescantia', 'Wanderjude', 7, 'partly', 'medium'),
	('Veitchia', '', 3, 'cloud', 'easy'),
	('Yucca', 'Palmlilie', 10, 'sun', 'easy'),
	('Zamioculcas', 'Glücksfeder', 10, 'cloud', 'easy');