name: Pull Request CI

on:
  pull_request_target:
    branches:
      - '**'
    types:
      - opened
      - edited
      - synchronize

defaults:
  run:
    working-directory: ./grow-green

jobs:
  set-labels:
    name: Set Labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler.yml
        sync-labels: true
  assign-author:
    name: Assign Author
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.1
  validate-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}